#pragma once

#define PV_MOUSE_BUTTON_LEFT	0x00
#define PV_MOUSE_BUTTON_RIGHT	0x01
#define PV_MOUSE_BUTTON_MIDDLE	0x02
#define PV_MOUSE_BUTTON_1		PV_MOUSE_BUTTON_LEFT
#define PV_MOUSE_BUTTON_2		PV_MOUSE_BUTTON_RIGHT
#define PV_MOUSE_BUTTON_3		PV_MOUSE_BUTTON_MIDDLE
#define PV_MOUSE_BUTTON_4		0x03
#define PV_MOUSE_BUTTON_5		0x04